# -*- coding: utf-8 -*-
"""HardDisk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17z7BhU0_dxZxCrqTBve1FYtCSgMvng3e
"""

!apt-get update
!apt-get install -y tesseract-ocr
!pip install pytesseract
!pip install Pillow

from PIL import Image, ImageEnhance, ImageFilter
import pytesseract
from google.colab import files

# 새로운 이미지 경로 리스트
new_image_paths = [
    "D.png",
    "E.png",
    "F.png",
    "G.png",
    "H.png"
]

# 각 이미지에서 텍스트 추출
new_extracted_texts = []
for path in new_image_paths:
    image = Image.open(path)
    text = pytesseract.image_to_string(image, lang='kor+eng')
    new_extracted_texts.append(text)

# 추출된 텍스트 출력
new_extracted_texts