# -*- coding: utf-8 -*-
"""금팔기_Greedy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1riLRX75-_de3Xf5DWyfu8KmYq0fxt8fG
"""

def max_profit_with_limits(prices, total_gold, k):
    # 현재 남은 금의 개수
    remaining_gold = total_gold

    # 금 가격을 높은 순서로 정렬하며, 해당 날 판매 가능한 금 개수 고려
    sorted_days = sorted([(price, i) for i, price in enumerate(prices)], reverse=True)

    total_profit = 0
    for price, day in sorted_days:
        if remaining_gold <= 0:
            break

        # 하루에 판매할 수 있는 금 개수는 k개 또는 남은 금 개수 중 작은 값
        gold_to_sell = min(k, remaining_gold)
        total_profit += gold_to_sell * price
        remaining_gold -= gold_to_sell

    return total_profit

# 테스트
prices1 = [1, 2, 10, 2, 5]
total_gold1 = 10
k1 = 3
print("결과:", max_profit_with_limits(prices1, total_gold1, k1))  # 출력: 67

prices2 = [5, 3, 6, 1, 4]
total_gold2 = 7
k2 = 2
print("결과:", max_profit_with_limits(prices2, total_gold2, k2))  # 출력: 38