# -*- coding: utf-8 -*-
"""닉네임규칙.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ug9ENbRgEXJceijB3wQjtLmH1cWPTJpi
"""

def solution(nickname):
    answer = ""
    for letter in nickname:
        if letter == "l":
            answer += "I"
        elif letter == "w":
            answer += "vv"
        elif letter == "W":
            answer += "VV"
        elif letter == "O":
            answer += "0"
        else:
            answer += letter
    while len(answer) <= 3:
        answer += "o"
    if len(answer) > 8:
        answer = answer[:8]
    return answer

print(solution("WORLDworld"))
print(solution("GO"))