# -*- coding: utf-8 -*-
"""달리기경주.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TYuZjgztNrjJKrBPoDPhqOh88jcq9-NQ
"""

def solution(players, callings):
    player_indices = {player: idx for idx, player in enumerate(players)}

    for calling in callings:
        # 호출된 플레이어의 인덱스를 찾고
        current_index = player_indices[calling]

        # 호출된 플레이어가 첫 번째가 아니면 앞의 플레이어와 위치를 교환
        if current_index > 0:
            # 앞의 플레이어 이름
            prev_player = players[current_index - 1]

            # 플레이어들 위치 교환
            players[current_index - 1], players[current_index] = players[current_index], players[current_index - 1]

            # 딕셔너리 업데이트
            player_indices[calling] -= 1
            player_indices[prev_player] += 1

    return players