# -*- coding: utf-8 -*-
"""두자리수_마다_더하기.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19YjpXhWfKCkKyF5dQnXGUlqQ2Goe3N9R
"""

number = int(input())

answer = 0

for i in range(len(str(number))):
    answer += number % 100
    number //= 100

print(answer)