# -*- coding: utf-8 -*-
"""문자출력.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13xEmgkYBG7W_Pi4NvMX74wBZwEs4CIMi
"""

message = "Let's go!"

print("3\n2\n1")
print(message)