# -*- coding: utf-8 -*-
"""버스.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1unMIYxYoGph_7LLhIkFR94zv64y6RCAI
"""

def func1(num):
    if 0 > num:
        return 0
    else:
        return num

def func2(num):
    if num > 0:
        return 0
    else:
        return num

def func3(station):
    num = 0
    for people in station:
        if people == "Off":
            num += 1
    return num

def func4(station):
    num = 0
    for people in station:
        if people == "On":
            num += 1
    return num


def solution(seat, passengers):
    num_passenger = 0
    for station in passengers:
        num_passenger += func4(station)
        num_passenger -= func3(station)

    answer = func1(seat-num_passenger)

    return answer

solution(10, [["On", "On", "On", "On", "On", "On", "On", "On", "-", "-"], ["On", "On", "Off", "Off", "Off", "On", "On", "-", "-", "-"], ["On", "On", "On", "Off", "On", "On", "On", "Off", "Off", "Off"], ["On", "On", "Off", "-", "-", "-", "-", "-", "-", "-"]])
solution(3, [["On", "On", "Off"], ["On", "On", "On", "Off"], ["On", "On", "On", "On"]])