# -*- coding: utf-8 -*-
"""병과분류.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jk_411XBioqXrHkmTPrMvz83ZB9SzRdk
"""

code = input()
last_four_words = code[-4:]

if last_four_words == "_eye":
    print("Ophthalmologyc")
elif last_four_words == "head":
    print("Neurosurgery")
elif last_four_words == "infl":
    print("Orthopedics")
elif last_four_words == "skin":
    print("Dermatology")
else:
    print("direct recommendation")