# -*- coding: utf-8 -*-
"""수조작2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jk_411XBioqXrHkmTPrMvz83ZB9SzRdk
"""

def solution(numLog):
    answer = ''
    temp = numLog[0]

    for i in range(len(numLog)):
        if numLog[i] == temp:
            continue
        elif numLog[i] - temp == 1:
            answer += 'w'
            temp = numLog[i]
        elif numLog[i] - temp == -1:
            answer += 's'
            temp = numLog[i]
        elif numLog[i] - temp == 10:
            answer += 'd'
            temp = numLog[i]
        elif numLog[i] - temp == -10:
            answer += 'a'
            temp = numLog[i]


    return answer