# -*- coding: utf-8 -*-
"""심폐소생술.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hhom5fyE9zX4HHPFCXbZaBIBZvSR8uSQ
"""

def solution(cpr):
    answer = []
    basic_order = ["check", "call", "pressure", "respiration", "repeat"]
    for action in cpr:
        for i in range(len(basic_order)):
            if action == basic_order[i]:
                answer.append(i+1)
    return answer

print(solution(["call", "respiration", "repeat", "check", "pressure"]))
print(solution(["respiration", "repeat", "check", "pressure", "call"]))